# fly.toml app configuration file generated for telehealth-frontend-cold-marsh-6485 on 2026-09-23T10:01:35+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'telehealth-frontend-cold-marsh-6485'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

  [build.args]
    VITE_API_BASE_URL = 'https://telehealth-backend-dry-mountain-2145.fly.dev'

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
